name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
          cache: true
          cache-dependency-path: packages/tui/go.sum

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Download Go modules
        run: cd packages/tui && go mod download

      - name: Install Node.js dependencies
        run: cd packages/tdd-pro && bun install

      - name: Build Node.js components
        run: cd packages/tdd-pro && bun run build

      - name: Build MCP server binaries
        run: cd packages/tdd-pro && bash scripts/build-mcp.sh

      - name: Run tests
        run: |
          cd packages/tdd-pro && npm run test:unit
          cd ../tui && go test ./...

      - name: Build with GoReleaser (snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/