name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
          cache: true
          cache-dependency-path: packages/tui/go.sum

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Download Go modules
        run: cd packages/tui && go mod download

      - name: Install Node.js dependencies
        run: cd packages/tdd-pro && bun install

      - name: Run tests
        run: |
          cd packages/tdd-pro && bun test
          cd ../tui && go test ./...

      - name: Publish
        run: |
          if [ "${{ startsWith(github.ref, 'refs/tags/') }}" = "true" ]; then
            TAG=${GITHUB_REF#refs/tags/}
            VERSION=${TAG#v}
            echo "Publishing version: $VERSION"
            VERSION=$VERSION ./scripts/publish.ts
          else
            echo "Running snapshot build..."
            ./scripts/publish.ts --dry
          fi
        working-directory: ./packages/tdd-pro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: ${{ github.event_name == 'workflow_dispatch' && 'build --snapshot --clean' || 'release --clean' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update install script compatibility
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo "✅ Install script is now compatible with release ${{ github.ref_name }}"
          echo "Users can run: curl -fsSL https://raw.githubusercontent.com/tdd-pro/tdd-pro/main/install | bash"